### ISSUE TITLE
Last styling pass through tabler theme

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/theme-tabler#35]

**Comment by tabacitu** [comment]
Hey @maurohmartinez ,

Here it is, I went through Theme-Tabler once to highlight what I see as quirks/todos/fixes-needed. It's before I had my coffee so please excuse my lack of enthusiasm 😅 

[![](https://cdn.loom.com/sessions/thumbnails/6954f122af35494c95522c027eeb5339-with-play.gif)](https://www.loom.com/share/6954f122af35494c95522c027eeb5339)

These are some minor things that do need fixing. This final pixel-pushing session should make Theme-Tabler look _polished_ so that we can start filming 💪 Let's do thissss!!

**Comment by maurohmartinez** [comment]
**Todo**

- [ ] My account: no space between cards
- [ ] My account: bolder titles in cards, check **Tabler**
- [ ] Dashboard: use display flex to keep same height for cards?
- [ ] Titles jump a bit on list operation
- [ ] Reset button on list operation doesn't look like a link
- [ ] Action column has blue buttons (when not displayed as a dropdown)
- [ ] Underline for action column buttons, looks weird (maybe no underline)
- [ ] Action links on show operation do not have margin between text <-> icon
- [ ] Print button should go to the right on show operation
- [ ] Back to list operation link doesn't look like a button
- [ ] Add margin between text <-> icon for bulk buttons on list operation
- [ ] Articles -> image filed, check box shadow
- [ ] Check all buttons, margin between text <-> icon
- [ ] Add buttons for inline operation are blue
- [ ] Checkbox, switch fields not properly aligned
- [ ] Create operation, check the title, link to "Back to list" looks different than in other operations
- [ ] Search field on list operation is not aligned as buttons above the table
- [ ] Order operation, when dragging looks too small, and no margin buttons in action buttons
- [ ] Date and date range filters, check margin in icon
